version: '3.8'

services:
  postgres:
    hostname: postgress
    container_name: postgres
    image: postgres:14.10
    environment:
      POSTGRES_USER: "${user}"
      POSTGRES_PASSWORD: "${password}"
      POSTGRES_DB: "${db_name}"
    env_file:
      - green.env
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      pg_network:

  pgadmin:
    hostname: pgadmin
    container_name: pgadmin
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "${pgadmin_user}"
      PGADMIN_DEFAULT_PASSWORD: "${pgadmin_password}"
    env_file:
      - green.env
    restart: always
    ports:
      - 8080:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      pg_network:

  panda:
    hostname: panda
    container_name: panda
    build:
      context: .
      dockerfile: Dockerfile-panda
    env_file:
      - green.env
    environment:
      - USER=${user}
      - PASSWORD=${password}
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
      - DB_NAME=${db_name}
      - TABLE_NAME=${table_name}
      - FILE_URL=${file_url}
      - ZONE_URL=${zone_url}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      pg_network:

networks:
  pg_network:

volumes:
  postgres-volume:
